version = 0.1

[default.global.parameters]
stack_name = "activity-environment-stage"

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
region = "us-east-1"
parameter_overrides = "Stage=stage"
